INSERT INTO items (name, description, price, stock, category, img, user_id) VALUES
('Handmade Wooden Bowl', 'A beautifully handcrafted wooden bowl.', 29.99, 15, 'Kitchenware', '/cosc-360-project/handmade_goods/assets/images/product_images/handmade_wooden_bowl.webp', 3),
('Knitted Scarf', 'A warm and cozy knitted scarf made from wool.', 19.99, 25, 'Clothing', '/cosc-360-project/handmade_goods/assets/images/product_images/knitted_scarf.webp', 4),
('Ceramic Vase', 'A stylish handmade ceramic vase.', 34.99, 12, 'Home Decor', '/cosc-360-project/handmade_goods/assets/images/product_images/ceramic_vase.webp', 5),
('Leather Wallet', 'A premium handmade leather wallet.', 49.99, 20, 'Accessories', '/cosc-360-project/handmade_goods/assets/images/product_images/leather_wallet.webp', 6),
('Hand-Painted Mug', 'A unique hand-painted ceramic mug.', 14.99, 30, 'Kitchenware', '/cosc-360-project/handmade_goods/assets/images/product_images/hand_painted_mug.webp', 7),
('Wooden Jewelry Box', 'A handcrafted wooden jewelry box with carvings.', 39.99, 12, 'Accessories', '/cosc-360-project/handmade_goods/assets/images/product_images/wooden_jewelry_box.webp', 8),
('Macrame Wall Hanging', 'A boho-style macrame wall hanging.', 24.99, 18, 'Home Decor', '/cosc-360-project/handmade_goods/assets/images/product_images/macrame_wall_hanging.webp', 9),
('Handmade Soap Set', 'A set of organic handmade soaps.', 12.99, 50, 'Personal Care', '/cosc-360-project/handmade_goods/assets/images/product_images/handmade_soap_set.webp', 2),
('Woven Basket', 'A natural fiber woven basket for storage.', 27.99, 22, 'Home Decor', '/cosc-360-project/handmade_goods/assets/images/product_images/woven_basket.webp', 3),
('Handcrafted Candle', 'A scented handmade candle with natural wax.', 16.99, 35, 'Personal Care', '/cosc-360-project/handmade_goods/assets/images/product_images/handcrafted_candle.webp', 2),
('Handwoven Table Runner', 'A beautifully handwoven table runner.', 32.99, 20, 'Home Decor', '/cosc-360-project/handmade_goods/assets/images/product_images/handwoven_table_runner.webp', 4),
('Beaded Necklace', 'A handmade beaded necklace with intricate designs.', 22.99, 15, 'Accessories', '/cosc-360-project/handmade_goods/assets/images/product_images/beaded_necklace.webp', 5),
('Crochet Blanket', 'A soft and cozy handmade crochet blanket.', 79.99, 10, 'Home Decor', '/cosc-360-project/handmade_goods/assets/images/product_images/crochet_blanket.webp', 6),
('Leather Keychain', 'A stylish handcrafted leather keychain.', 9.99, 40, 'Accessories', '/cosc-360-project/handmade_goods/assets/images/product_images/leather_keychain.webp', 7),
('Hand-Stitched Notebook', 'A unique hand-stitched leather-bound notebook.', 18.99, 25, 'Stationery', '/cosc-360-project/handmade_goods/assets/images/product_images/hand_stitched_notebook.webp', 8),
('Rustic Wooden Coasters', 'A set of four handcrafted rustic wooden coasters.', 14.99, 30, 'Kitchenware', '/cosc-360-project/handmade_goods/assets/images/product_images/rustic_wooden_coasters.webp', 9),
('Handmade Plush Toy', 'A cute and soft handmade plush toy.', 26.99, 12, 'Toys', '/cosc-360-project/handmade_goods/assets/images/product_images/handmade_plush_toy.webp', 2),
('Bamboo Cutting Board', 'A durable handmade bamboo cutting board.', 39.99, 20, 'Kitchenware', '/cosc-360-project/handmade_goods/assets/images/product_images/bamboo_cutting_board.webp', 3),
('Macrame Plant Hanger', 'A trendy handmade macrame plant hanger.', 17.99, 25, 'Home Decor', '/cosc-360-project/handmade_goods/assets/images/product_images/macrame_plant_hanger.webp', 4),
('Hand-Carved Wooden Spoon Set', 'A set of hand-carved wooden spoons.', 22.99, 18, 'Kitchenware', '/cosc-360-project/handmade_goods/assets/images/product_images/hand_carved_wooden_spoons.webp', 5),
('Handwoven Picnic Basket', 'A beautifully woven picnic basket.', 44.99, 10, 'Home Decor', '/cosc-360-project/handmade_goods/assets/images/product_images/handwoven_picnic_basket.webp', 6),
('Recycled Glass Bottle Vase', 'An eco-friendly vase made from recycled glass.', 29.99, 8, 'Home Decor', '/cosc-360-project/handmade_goods/assets/images/product_images/recycled_glass_vase.webp', 7),
('Embroidered Tote Bag', 'A stylish handmade embroidered tote bag.', 27.99, 15, 'Accessories', '/cosc-360-project/handmade_goods/assets/images/product_images/embroidered_tote_bag.webp', 8),
('Handmade Soy Wax Melts', 'A set of scented soy wax melts.', 12.99, 40, 'Personal Care', '/cosc-360-project/handmade_goods/assets/images/product_images/handmade_soy_wax_melts.webp', 9),
('Knitted Wool Mittens', 'Warm and cozy hand-knitted wool mittens.', 23.99, 30, 'Clothing', '/cosc-360-project/handmade_goods/assets/images/product_images/knitted_wool_mittens.webp', 3),
('Custom Calligraphy Sign', 'A handmade wooden sign with custom calligraphy.', 37.99, 12, 'Home Decor', '/cosc-360-project/handmade_goods/assets/images/product_images/custom_calligraphy_sign.webp', 4),
('Wooden Hair Comb', 'A hand-carved wooden hair comb.', 15.99, 20, 'Personal Care', '/cosc-360-project/handmade_goods/assets/images/product_images/wooden_hair_comb.webp', 5),
('Herbal Bath Salts', 'A set of handmade herbal bath salts.', 19.99, 25, 'Personal Care', '/cosc-360-project/handmade_goods/assets/images/product_images/herbal_bath_salts.webp', 6),
('Rustic Wooden Photo Frame', 'A beautifully rustic handmade photo frame.', 21.99, 18, 'Home Decor', '/cosc-360-project/handmade_goods/assets/images/product_images/rustic_wooden_photo_frame.webp', 7);
